services:
  - type: web
    name: tracker-mobile-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/check_connection
